version: '3.8'

services:

  nginx:
    container_name: docker-dev-nginx
    image: nginx:1.21.3-alpine
    ports:
      - "8080:80"
    depends_on:
      - php
      - phpmyadmin
    volumes:
      - ./code:/var/www/code
      - ./nginx/conf.d:/etc/nginx/conf.d
      - phpmyadmindata:/var/www/phpmyadmin
    networks:
      - dev-network

  php:
    container_name: docker-dev-php
    build:
      context: ./
      args:
        UID: $UID
        UNIX_PASSWD: $UNIX_PASSWD
    expose:
      - 9003
    working_dir: /var/www/code
    depends_on:
      - mysql
    volumes:
      - ./code:/var/www/code
      - ./home/user/.gitconfig:/home/user/.gitconfig
    networks:
      - dev-network

  mysql:
    container_name: docker-dev-mysql
    image: mariadb:10.6.4-focal
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - dev-network

  phpmyadmin:
    container_name: docker-dev-phpmyadmin
    image: phpmyadmin:5.1.1-fpm-alpine
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    volumes:
      - phpmyadmindata:/var/www/html
    networks:
      - dev-network

volumes:
  mysqldata:
    driver: local
  phpmyadmindata:
    driver: local

networks:
  dev-network:
    driver: bridge
