version: '3.8'

services:

  nginx:
    container_name: docker-dev-nginx
    image: nginx:1.21.6-alpine
    ports:
      - "80:80"
    depends_on:
      - php
      - phpmyadmin
    volumes:
      - ./code:/var/www/code
      - ./nginx/conf.d:/etc/nginx/conf.d
      - phpmyadmindata:/var/www/phpmyadmin
    networks:
      - dev-network

  php:
    container_name: docker-dev-php
    build:
      context: ./
      args:
        UID: $UID
        UNIX_PASSWD: $UNIX_PASSWD
    expose:
      - 9003
    working_dir: /var/www/code
    depends_on:
      - mysql
    volumes:
      - ./code:/var/www/code
    networks:
      - dev-network

  mysql:
    container_name: docker-dev-mysql
    image: mariadb:10.7.3-focal
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - dev-network

  phpmyadmin:
    container_name: docker-dev-phpmyadmin
    image: phpmyadmin:5.1.3-fpm-alpine
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_PASSWD}
    depends_on:
      - mysql
    volumes:
      - phpmyadmindata:/var/www/html
    networks:
      - dev-network

volumes:
  mysqldata:
    driver: local
  phpmyadmindata:
    driver: local

networks:
  dev-network:
    driver: bridge
