version: '3.8'

services:

  nginx:
    image: nginx:1.21.3
    ports:
      - "8080:80"
    volumes:
      - ./src/backend:/var/www/backend
      - ./nginx/conf.d:/etc/nginx/conf.d
      - phpmyadmindata:/var/www/phpmyadmin
    depends_on:
      - backend
      - phpmyadmin

  backend:
    build: ./
    working_dir: /var/www/backend
    volumes:
      - ./src/backend:/var/www/backend
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    volumes:
      - mysqldata:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin:5.1.1-fpm-alpine
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      - mysql

volumes:

  mysqldata:
  
  phpmyadmindata: